version: '3'
services:
  web:
    image: nginx:latest
    container_name: translate_web
    ports:
      - 8080:80
    volumes:
      - ./app:/app
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build: .
    container_name: translate_php
    volumes:
      - ./app:/app
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=root
      - DB_DATABASE=translate
    links:
      - db
  db:
    image: mariadb:latest
    container_name: translate_db
    volumes:
      - ./config/db.sql:/tmp/db.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=translate
